config/routes.rb
Rails.application.routes.draw do
  get 'events/show'

  resources :embeds, only: :show, path: 'embed' # -> domain.com/embed/:id

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

	def allow_iframe
	  response.headers.delete 'X-Frame-Options'
	end
end

app/controllers/embeds_controller.rb
class EmbedsController < ApplicationController
  after_filter :allow_iframe, only: [:show]
  protect_from_forgery except: [:show]

  layout false

  def show
    @content = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def show
  	@content = Event.find(params[:id])
  	respond_to do |format|
			format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/embeds/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="content-wrapper">
      <%= render partial: 'shared/embed', locals: { content: @content } %>
    </div>
  </body>

</html>

app/views/events/show.html.erb
 <div class="content-wrapper">
  <%= @content.title %> - <%= @content.description %>
  <%= link_to "Next Event", events_show_path(id: @content.id + 1) %>
</div>

app/views/events/show.js.erb
$(".content-wrapper").html("<%= escape_javascript(render partial: 'shared/embed', locals: { content: @content } ) %>"); 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WidgetDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_embed.html.erb
<%= @content.title %> - <%= @content.description %>
<%= link_to "Next Event", events_show_path(id: @content.id + 1), remote: true %>

<%= react_component('TestTags') %>
<script>ReactRailsUJS.mountComponents()</script>